#allows you to define and manage multi-container applications in a single YAML file

name: my-socialMedia-project

services:
    app:
      build: .
      image: my-docker-image
      container_name: my-SocialMediaApp-container
      command: python manage.py runserver 0.0.0.0:8000
      ports:
        - "8000:8000"
      volumes:
        - .:/app
      env_file:
        - ./SocialMediaWebsite/.env
      depends_on:
        - postgres

    postgres:
      image: postgres
      container_name: my-postgres-container
      ports:
        - "5432:5432"
      environment:
        POSTGRES_DB: postgres
        POSTGRES_USER : postgres
        POSTGRES_PASSWORD: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      env_file:
        - ./SocialMediaWebsite/.env


volumes:
  postgres_data: 