# Generated by Django 5.0.2 on 2024-05-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_post_upload_alter_profile_profileimg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post_upload",
            name="image",
            field=models.ImageField(upload_to="post_images"),
        ),
    ]
