# Generated by Django 5.0.2 on 2024-05-12 04:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0005_alter_followerscount_follower_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profileImg",
            field=models.ImageField(
                default="images/blank-profile-picture.png", upload_to="profile_images"
            ),
        ),
    ]
